---
- include_role:
    name: andrewrothstein.unarchive-deps
- include_role:
    name: andrewrothstein.alpineglibcshim
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: mkdir {{ openjdk_install_dir }}
  become: true
  become_user: root
  file:
    path: '{{ openjdk_install_dir }}'
    state: directory
    mode: 0755
- name: looking for install subdir at {{ openjdk_install_subdir }}...
  become: true
  become_user: root
  stat:
    path: '{{ openjdk_install_subdir }}'
  changed_when: false
  register: openjdk_binary
- when: not openjdk_binary.stat.exists
  block:
    - name: downloading {{ openjdk_archive_url }}...
      become: true
      become_user: root
      get_url:
        url: '{{ openjdk_archive_url }}'
        dest: '{{ openjdk_tmp_archive }}'
        checksum: '{{ openjdk_checksum }}'
        mode: 0644
    - name: unarchiving {{ openjdk_tmp_archive }} to {{ openjdk_install_dir }}...
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ openjdk_tmp_archive }}'
        dest: '{{ openjdk_install_dir }}'
        creates: '{{ openjdk_install_subdir }}'
  always:
    - name: deleting {{ openjdk_tmp_archive }}...
      become: true
      become_user: root
      file:
        path: '{{ openjdk_tmp_archive }}'
        state: absent
- name: linking {{ openjdk_install_link }} to {{ openjdk_install_subdir }}...
  become: true
  become_user: root
  file:
    src: '{{ openjdk_install_subdir }}'
    dest: '{{ openjdk_install_link }}'
    state: link
- name: adding openjdk to default path and easing systemd integration...
  become: true
  become_user: root
  with_items:
    - f: openjdk.sh
      d: /etc/profile.d
    - f: openjdk.env
      d: '{{ openjdk_install_subdir }}'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'
